### ISSUE TITLE
No error for incorrect postal codes

### ISSUE THREAD

**Issue by redon92** [axlon/laravel-postal-code-validation#11]
It doesn't show any error for incorrect postal codes, for example if i insert a postal code 55555 for IT (Italy), and it doesn't show any error. 
All it does is check if the inserted postal code has the postal code length of that country:

`'pattern' => '/^\d{5}$/i',`

I suggest you submit postal codes from the world in this package, and then it would be available to laravel users, and updated accordingly, to avoid such problems.

**Comment by axlon** [comment]
This package uses [Google's address data service](https://github.com/google/libaddressinput/wiki/AddressValidationMetadata) to create rules a postal code in a given country should follow. 

Some countries have prefixes or suffixes and are very specific in what they will allow (e.g. UK), but for some countries there simply isn't a better pattern than the one provided.
