### ISSUE TITLE
Allow spaces in postcode

### ISSUE THREAD

**Issue by ChappersJr** [axlon/laravel-postal-code-validation#15]
Hey,

I've just had another potential issue but this one is more of a suggestion that a bug.

A Customer entered the postcode: 'CF 242NY'

This came back as an invalid UK postcode.

We don't want to strip white space from the postcodes before posting to a form request but we still want it to pass validation. Is it possible to ignore whitespace when validating a UK postcode?

**Comment by axlon** [comment]
This is the pattern from [Google's API](https://www.gstatic.com/chrome/autofill/libaddressinput/chromium-i18n/ssl-address/data/GB): 
```
GIR ?0AA|(?:(?:AB|AL|B|BA|BB|BD|BF|BH|BL|BN|BR|BS|BT|BX|CA|CB|CF|CH|CM|CO|CR|CT|CV|CW|DA|DD|DE|DG|DH|DL|DN|DT|DY|E|EC|EH|EN|EX|FK|FY|G|GL|GY|GU|HA|HD|HG|HP|HR|HS|HU|HX|IG|IM|IP|IV|JE|KA|KT|KW|KY|L|LA|LD|LE|LL|LN|LS|LU|M|ME|MK|ML|N|NE|NG|NN|NP|NR|NW|OL|OX|PA|PE|PH|PL|PO|PR|RG|RH|RM|S|SA|SE|SG|SK|SL|SM|SN|SO|SP|SR|SS|ST|SW|SY|TA|TD|TF|TN|TQ|TR|TS|TW|UB|W|WA|WC|WD|WF|WN|WR|WS|WV|YO|ZE)(?:\\d[\\dA-Z]? ?\\d[ABD-HJLN-UW-Z]{2}))|BFPO ?\\d{1,4}
```

As you can see, its quite complex, so I'd prefer not messing with it if possible.

This can probably be solved by stripping the input of whitespaces inside the validation rules right before they run the actual validation.

Feel free to create a PR for this :)

**Comment by ChappersJr** [comment]
I'm against my own suggestion now :)

I don't want to allow any amounts of white space for such a minor issue. I'll come up with a solution that doesn't involve modifying such a good package.
