### ISSUE TITLE
  If I want state verification

### ISSUE THREAD

**Issue by zqh375** [axlon/laravel-postal-code-validation#25]

**Comment by axlon** [comment]
@zqh375 Please provide more information

**Comment by djurovicigoor** [comment]
I'm not sure what @zqh375 needs, but maybe I need something similar. How can I validate my postal code along with the US state code?

@axlon

**Comment by axlon** [comment]
@djurovicigoor this is currently not supported by this library, I've looked into supporting this (as well as sub localities in Canada, Japan, China, and others) in the past but haven't gotten around to it as it does require some components of this package to be rebuilt.
