### ISSUE TITLE
Dutch Postal Code matches invalid postcode

### ISSUE THREAD

**Issue by roelofr** [axlon/laravel-postal-code-validation#27]
- PHP: n/a
- Laravel: n/a
- Postal code validation: master @ d6341761d0eab7c229bac1f0108a774b0439b2ce (resolved from code on GitHub)

### Description:

The Dutch regex matches invalid postal codes on two parts:

1. The postcodes cannot start with a `0`, but the regex allows this.
2. The postcodes cannot end with `SA`, `SD` or `SS` due to the reference to the [Stormabteilung][1], [Sicherheitsdienst][2] and the [Shutzstaffel][3]. Credit to @wotta for learning me about this.

[1]: https://en.wikipedia.org/wiki/Sturmabteilung
[2]: https://en.wikipedia.org/wiki/Sicherheitsdienst
[3]: https://en.wikipedia.org/wiki/Schutzstaffel

### Steps To Reproduce:

1. Validate against `0123 AB`, `1111 SA` or `5949 SS`
2. Get accepted as valid input

**Comment by axlon** [comment]
Hey @roelofr thanks for pointing this out, you should probably create an issue at [google/libaddressinput](https://github.com/google/libaddressinput/issues) where this data is seeded from.

**Comment by axlon** [comment]
Closing this for now
