### ISSUE TITLE
[PROPOSAL] Add required format to the error message

### ISSUE THREAD

**Issue by bilfeldt** [axlon/laravel-postal-code-validation#3]
It would be a really nice addon to the validation if the error message could contain the required postal code format for the given country.

The docs has [this section](https://github.com/axlon/laravel-postal-code-validation#adding-an-error-message):

> To add an error message your users will be able to understand, open resources/lang/{your language}/validation.php and add the following line to it:
> ```
> 'postal_code' => 'The :attribute field must be a valid postal code.',
> ```

Imagine instead an error message like:
```
'postal_code' => 'The :attribute field must be a valid postal code with format :format.',
```

This can be done using the `$validator->addReplacer()` method described [here](https://laravel.com/api/5.8/Illuminate/Validation/Validator.html#method_addReplacer). Unfortunatly I am not really sure where would be the best place in the code for placing this.

Would this feature be of interest?

**Comment by axlon** [comment]
This would be a nice feature to have, the only question is how should we handle countries that have multiple formats?

Feel free to submit a PR!

**Comment by bilfeldt** [comment]
For countries with multiple acceptable formats then I suggest showing them comma separated. Examples:
```
'The postal code field must be a valid postal code with format ####',//Example from AT
'The postal code field must be a valid postal code with format #####', #####-####',//Example from AS
```
If this is something you would be willing to merge, then I will try to make a PR for this.

It [seems](https://github.com/sirprize/postal-code-validator/blob/c2d6c0f1772f46af33898c7742aaaa51fccf35d9/lib/Sirprize/PostalCodeValidator/Validator.php#L331) that we should be able to get the formats as an array using:
```
$this->engine->getFormats($countryCode)
```

**Comment by axlon** [comment]
@bilfeldt see the new version [v1.4.0](https://github.com/axlon/laravel-postal-code-validation/tree/v1.4.0).
