### ISSUE TITLE
Optional postcode not possible

### ISSUE THREAD

**Issue by Jamesking56** [axlon/laravel-postal-code-validation#30]
- PHP: 7.4.28
- Laravel: 8.83.2
- Postal code validation: 3.3.0

### Description:

I am trying to make an optional postcode field, so that it can either be blank or be a valid postcode only.

This doesn't seem to be possible, as the validator checks a blank empty string value and errors that it is not a valid postal code

### Steps To Reproduce:

Create a Validator with rule `['postcode' => 'postal_code:GB']` and POST an empty postal code to it. Notice I haven't added `required`, so it should treat the field as optional but it has the validation error.

**Comment by axlon** [comment]
Hello @Jamesking56, 

I tried to reproduce this with the following code, but was unable to:

```php
$data = Validator::validate(['foo' => ''], ['foo' => 'postal_code:GB']);
dd($data);
```

Results in the following for me:

```php
[
    'foo' => '',
];
```

Laravel is the one that handles `sometimes`, `nullable`, and `required` and determines if rules should be run on a field or not, and we don't really have control over this in userland.

Does the problem persist if you change `postal_code:GB` to `int` for instance?

**Comment by Jamesking56** [comment]
Hi @axlon 

I had to override your Rule in the end with my own and allow the field to not be present so not entirely sure why you can't reproduce it.

What happens when you provide an empty POST body with your rule? So the `foo` key is not present at all?

Cheers.

**Comment by axlon** [comment]
When I provide an empty body the rule is skipped (which is done by Laravel, the package has no control over this behavior). Do you have a snippet of code that would allow me to reproduce the issue?
