### ISSUE TITLE
Laravel 10 support

### ISSUE THREAD

**Issue by schonhoff** [axlon/laravel-postal-code-validation#32]
Hey!

### Description
Will Laravel 10 be supported for this package? It was released today.
Thanks for the great package. Helped me out a lot and would love to use it still in the future.

**Comment by axlon** [comment]
Feel free to open a PR

**Comment by schonhoff** [comment]
I opened a PR https://github.com/axlon/laravel-postal-code-validation/pull/33 Maybe you can check if all things are okay with it. My tests were green for Lumen 9 and Laravel 10.

**Comment by axlon** [comment]
Version 3.4.0 is now tagged
