### ISSUE TITLE
The Canary Islands ISO 3166-1 alpha-2 Code

### ISSUE THREAD

**Issue by RalpinMcDjango** [axlon/laravel-postal-code-validation#35]
### Description
The Canary Islands have a unique exceptionally reserved [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) code. The format is the same as the Spanish code `ES`, the islands are a Spanish autonomous community.

Multiple shipping couriers we have directly integrated with expect the more specific `IC` country code to be passed when booking a shipment.

We currently cannot validate a customer's country on the front end as this library does not support the `IC` code, so we have to validate and store the country as Spain but we then cannot pass that data onto shipping providers as they expect the more specific `IC` county code.

We have had to implement a workaround to resolve this when pushing data into the relevant courier APIs.

### Example
The postal code of `38580` validates perfectly when using the `ES` country code as expected.
```
 PostalCode::for('ES');
```
But it fails when using The Canary Islands ISO 3166-1 alpha-2 code `IC`.
```
 PostalCode::for('IC');
```

### Solution
We would like to see the IC country code added into the `patterns.php` file using the regex pattern of the Spanish `ES` country code.
```
    'HR' => '/^(?:\d{5})$/i',
    'HT' => '/^(?:\d{4})$/i',
    'HU' => '/^(?:\d{4})$/i',
    'IC' => '/^(?:\d{5})$/i',
    'ID' => '/^(?:\d{5})$/i',
    'IE' => '/^(?:[\dA-Z]{3} ?[\dA-Z]{4})$/i',
```

I apologise if this would of been more suited as a bug report but everything with the `ES` country code is working as expected.

**Comment by axlon** [comment]
Hello @RalpinMcDjango, support for the Canary Islands has been added, please check the [latest release](https://github.com/axlon/laravel-postal-code-validation/releases/tag/v3.7.0)

**Comment by RalpinMcDjango** [comment]
> Hello @RalpinMcDjango, support for the Canary Islands has been added, please check the [latest release](https://github.com/axlon/laravel-postal-code-validation/releases/tag/v3.7.0)

Amazing, thank you so much for looking at this so quickly.
